### ISSUE TITLE
DJI P4 drone class

### ISSUE THREAD

**Issue by NickMortimer** [oceanhackweek/ohw23_proj_drone_georef#5]
```[tasklist]
### Tasks
- [x] Import DJI Class to the project
- [ ] Refactor it for this project
- [ ] Build test scripts
```

**Comment by NickMortimer** [comment]
https://github.com/dronemapper-io/dji-dewarp/blob/master/README.md

My code is based on this

**Comment by pbranson** [comment]
I think we should consider trying to use PyTorch3D for the camera models: https://pytorch3d.org/docs/cameras

**Comment by pbranson** [comment]
There is some discussion about the different camera conventions here: https://github.com/facebookresearch/pytorch3d/issues/522

**Comment by pbranson** [comment]
See https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/camera_conversions.py

**Comment by pbranson** [comment]
Nick suggested looking at this library which also has some nice simple descriptions for camera's - need to check the coordinate reference system. https://cameratransform.readthedocs.io/en/latest/spatial.html#camorientation
