### ISSUE TITLE
Run the test data through open drone map

### ISSUE THREAD

**Issue by NickMortimer** [oceanhackweek/ohw23_proj_drone_georef#7]
```[tasklist]
### Tasks
- [x] Install open drone map
- [ ] Get extracted gps positions and submit to open drone map
- [ ] Find camera intrinsics from open drone map
```
